In [1]:
install.packages("mlogit")
library(mlogit)

Installing package into 'C:/Users/jet_v/AppData/Local/R/win-library/4.4'
(as 'lib' is unspecified)

  There is a binary version available but the source version is later:
       binary source needs_compilation
mlogit  1.1-3  2.0-0             FALSE

installing the source package 'mlogit'

In [2]:
d <- read.csv("Commute_Mode.csv", header = TRUE)
summary(d)

       id          mode               choice          cost
 Min.   :  1   Length:1812        Min.   :0.00   Min.   :0.1293
 1st Qu.:114   Class :character   1st Qu.:0.00   1st Qu.:1.7979
 Median :227   Mode  :character   Median :0.00   Median :2.2493
 Mean   :227                      Mean   :0.25   Mean   :2.7018
 3rd Qu.:340                      3rd Qu.:0.25   3rd Qu.:2.8983
 Max.   :453                      Max.   :1.00   Max.   :8.8555
      time
 Min.   : 1.969
 1st Qu.:26.470
 Median :40.030
 Mean   :39.061
 3rd Qu.:52.061
 Max.   :75.681

In [3]:
head(d)

  id mode    choice cost     time
1 1  bus     0      1.800512 20.86779
2 1  car     1      1.507010 18.50320
3 1  carpool 0      2.335612 26.33823
4 1  rail    0      2.358920 30.03347
5 2  bus     0      2.237128 67.18189
6 2  car     0      6.056998 31.31111

In [5]:
commute <- mlogit.data(d, shape = "long", choice = "choice", alt.var = "mode", chid.var = "id")
head(commute)

~~~~~~~
 first 10 observations out of 1812
~~~~~~~
   id    mode choice     cost     time    idx
1   1     bus  FALSE 1.800512 20.86779  1:bus
2   1     car   TRUE 1.507010 18.50320  1:car
3   1 carpool  FALSE 2.335612 26.33823 1:pool
4   1    rail  FALSE 2.358920 30.03347 1:rail
5   2     bus  FALSE 2.237128 67.18189  2:bus
6   2     car  FALSE 6.056998 31.31111  2:car
7   2 carpool  FALSE 2.896919 34.25696 2:pool
8   2    rail   TRUE 1.855450 60.29313 2:rail
9   3     bus  FALSE 2.576385 63.30906  3:bus
10  3     car   TRUE 5.794677 22.54743  3:car

~~~ indexes ~~~~
   chid     alt
1     1     bus
2     1     car
3     1 carpool
4     1    rail
5     2     bus
6     2     car
7     2 carpool
8     2    rail
9     3     bus
10    3     car
indexes:  1, 2

In [7]:
ml.res <- mlogit(choice~cost+time, commute)
summary(ml.res)

Call:
mlogit(formula = choice ~ cost + time, data = commute, method = "nr")

Frequencies of alternatives:choice
    bus     car carpool    rail
0.17881 0.48124 0.07064 0.26932

nr method
5 iterations, 0h:0m:0s
g'(-H)^-1g = 6.07E-07
gradient close to zero

Coefficients :
                      Estimate Std. Error  z-value  Pr(>|z|)
(Intercept):car      3.2924661  0.3172767  10.3773 < 2.2e-16 ***
(Intercept):carpool -0.9051585  0.2459427  -3.6804 0.0002329 ***
(Intercept):rail     0.6277690  0.1633612   3.8428 0.0001216 ***
cost                -0.7723478  0.0919795  -8.3970 < 2.2e-16 ***
time                -0.0853574  0.0077484 -11.0161 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -354.45
McFadden R^2:  0.34811
Likelihood ratio test : chisq = 378.56 (p.value = < 2.22e-16)

In [8]:
head(fitted(ml.res, outcome = FALSE))

  bus         car       carpool     rail
1 0.023239855 0.9599263 0.003898082 0.012935746
2 0.025219334 0.7587305 0.101824644 0.114225571
3 0.010361942 0.7531561 0.179627373 0.056854613
4 0.051006926 0.8205847 0.005177723 0.123230683
5 0.001192494 0.9824974 0.013929585 0.002380538
6 0.108646984 0.7272479 0.153758333 0.010346785

In [10]:
cost.avg <- tapply(commute$cost, commute$alt, mean)
cost.avg
time.avg <- tapply(commute$time, commute$alt, mean)
time.avg
xval <- data.frame(cost = cost.avg, time = time.avg)
xval

     bus      car  carpool     rail
2.035669 4.873487 1.686348 2.211683

     bus      car  carpool     rail
39.92341 37.04412 39.77101 39.50451

        cost     time
bus     2.035669 39.92341
car     4.873487 37.04412
carpool 1.686348 39.77101
rail    2.211683 39.50451

In [15]:
effects(ml.res, covariate = "time", data = xval)

        bus          car          carpool       rail
bus     -0.010359065  0.006554077  0.0009151041  0.002889884
car      0.006554080 -0.021179563  0.0035174460  0.011108038
carpool  0.000915104  0.003517445 -0.0059834926  0.001550944
rail     0.002889884  0.011108035  0.0015509442 -0.015548863